<?php
# automatically generated by makeclasses.php

class UserEntity extends Entity {
	function __construct() {
		parent::__construct(
			FrametestDB::$db, 
			# $this->schema: for building forms among other things
			array ( 
				'email' => array ( 'type' => 'varchar', 'size' => 128, 'key' => true, ), 
				'password' => array ( 'type' => 'varchar', 'size' => 64, ), 
				'perms' => array ( 'type' => 'varchar', 'size' => 64, ), 
			),
			'user'
		);
	}

}
