<?php
# automatically generated by makeclasses.php

class ViewersRelation extends Relation {
	function __construct() {
		parent::__construct(
			FrametestDB::$db, 
			# $this->schema: for building forms among other things
			array ( 
				'PRIMARY KEY' => array ( 'email' => '', 'numbered_id' => 'numbered', ), 
				'email' => array ( 'type' => 'varchar', 'size' => 128, ), 
				'numbered_id' => array ( 'type' => 'int', 'size' => 11, ), 
			),
			'viewers'
		);
	}

}
