<?php
# automatically generated by makeclasses.php

class ClientsEntity extends Entity {
	function __construct() {
		parent::__construct(
			IntouchDB::$db, 
			# $this->schema: for building forms among other things
			array (
			  'id' => 
			  array (
			    'type' => 'int',
			    'size' => 11,
			    'key' => true,
			    'auto' => 1,
			  ),
			  'status' => 
			  array (
			    'type' => 'enum',
			    'opts' => 
			    array (
			      0 => 'active',
			      1 => 'inactive',
			      2 => 'deleted',
			    ),
			  ),
			  'name' => 
			  array (
			    'type' => 'varchar',
			    'size' => 64,
			  ),
			  'email' => 
			  array (
			    'type' => 'varchar',
			    'size' => 64,
			  ),
			  'notes' => 
			  array (
			    'type' => 'text',
			  ),
			  'created' => 
			  array (
			    'type' => 'datetime',
			  ),
			  'modified' => 
			  array (
			    'type' => 'timestamp',
			  ),
			  'callbackwait' => 
			  array (
			    'type' => 'int',
			    'size' => 11,
			  ),
			),
			'clients'
		);
	}

}
