<?php
# automatically generated by makeclasses.php

class FilesEntity extends Entity {
	function __construct() {
		parent::__construct(
			IntouchDB::$db, 
			# $this->schema: for building forms among other things
			array (
			  'clientid' => 
			  array (
			    'type' => 'int',
			    'size' => 11,
			  ),
			  'callerid' => 
			  array (
			    'type' => 'varchar',
			    'size' => 32,
			  ),
			  'filename' => 
			  array (
			    'type' => 'text',
			    'key' => true,
			  ),
			  'created' => 
			  array (
			    'type' => 'datetime',
			  ),
			  'modified' => 
			  array (
			    'type' => 'timestamp',
			  ),
			  'callbackts' => 
			  array (
			    'type' => 'double',
			  ),
			  'iscallback' => 
			  array (
			    'type' => 'int',
			    'size' => 11,
			  ),
			),
			'files'
		);
	}

}
