<?php
#autogenerated by mysql2schema.pl

# define the constants elsewhere - preferably where outsiders can't see them
$db = array(
	'host' => DBHOST,
	'login' => DBLOGIN,
	'pw' => DBPW,
	'db' => DBNAME,
);

$schema = array();

$schema['admins'] = array(
	# login is the primary key but I've removed the key => true
	'login' => array( 'type' => 'varchar', 'size' => 64, ), 
	'password' => array( 'type' => 'varchar', 'size' => 64, ),
	'created' => array( 'type' => 'datetime', ),
	'modified' => array( 'type' => 'timestamp', ),
	'perms' => array( 'type' => 'enum', ),
	'notes' => array( 'type' => 'varchar', 'size' => 255, ),
);

$schema['alerts'] = array(
	'PRIMARY KEY' => array('worker_id' => 'worker', 'alertsent' => '', ),
	'worker_id' => array( 'type' => 'int', 'size' => 11, ),
	'alertsent' => array( 'type' => 'datetime', ),
	'status' => array( 'type' => 'varchar', 'size' => 32, ),
	'emails' => array( 'type' => 'text', ),
);

$schema['checkins'] = array(
	'PRIMARY KEY' => array('worker_id' => 'worker', 'checkedin' => '', ),
	'worker_id' => array( 'type' => 'int', 'size' => 11, ),
	'checkedin' => array( 'type' => 'datetime', ),
);

$schema['files'] = array(
	'path' => array( 'type' => 'varchar', 'size' => 255, 'key' => true, ),
	'worker_id' => array( 'type' => 'int', 'size' => 11, ),
	'uploaded' => array( 'type' => 'datetime', ),
);

$schema['worker'] = array(
	'worker_id' => array( 'type' => 'int', 'size' => 11, 'key' => true, 'alt' => 'new worker', ),
	'name' => array( 'type' => 'varchar', 'size' => 64, ),
	'handle' => array( 'type' => 'varchar', 'size' => 64, ),
	'city' => array( 'type' => 'varchar', 'size' => 64, 'template' => 'tools/cities.tpl', ),
	'neighbourhood' => array( 'type' => 'varchar', 'size' => 64, ),
	'password' => array( 'type' => 'password', 'size' => 32, 'hide' => true, ),
	'voicemail' => array( 'type' => 'varchar', 'size' => 64, 'template' => 'tools/vm.tpl', ),
	'status' => array( 'type' => 'varchar', 'size' => 20, 'template' => 'workers/status.tpl', ),
	'notes' => array( 'type' => 'text', 'template' => 'workers/descriptionlink.tpl', ),
);

