<?php
# automatically generated by makeclasses.php

class BoxesEntity extends Entity {
	function __construct() {
		parent::__construct(
			LifelineDB::$db, 
			# $this->schema: for building forms among other things
			array ( 
				'box' => array ( 'type' => 'varchar', 'size' => 32, 'key' => true, ), 
				'name' => array ( 'type' => 'varchar', 'size' => 64, ), 
				'notes' => array ( 'type' => 'varchar', 'size' => 255, ), 
				'seccode' => array ( 'type' => 'varchar', 'size' => 32, ), 
				'email' => array ( 'type' => 'varchar', 'size' => 64, ), 
				'paidto' => array ( 'type' => 'date', ), 
				'inuse' => array ( 'type' => 'int', 'size' => 11, ), 
				'new_msgs' => array ( 'type' => 'int', 'size' => 11, ), 
				'reminder' => array ( 'type' => 'int', 'size' => 11, ), 
				'status' => array ( 'type' => 'varchar', 'size' => 32, ), 
				'vid' => array ( 'type' => 'int', 'size' => 11, ), 
				'login' => array ( 'type' => 'varchar', 'size' => 64, ), 
				'created' => array ( 'type' => 'datetime', ), 
				'trans' => array ( 'type' => 'varchar', 'size' => 32, ), 
				'llphone' => array ( 'type' => 'varchar', 'size' => 32, ), 
				'announcement' => array ( 'type' => 'int', 'size' => 11, ), 
				'canremove' => array ( 'type' => 'int', 'size' => 11, ), 
				'modified' => array ( 'type' => 'timestamp', ), 
			),
			'boxes'
		);
	}

}
