<?php
# automatically generated by makeclasses.php

class EmailsignupEntity extends Entity {
	function __construct() {
		parent::__construct(
			LifelineDB::$db, 
			# $this->schema: for building forms among other things
			array ( 
				'vid' => array ( 'type' => 'int', 'size' => 11, ), 
				'email' => array ( 'type' => 'varchar', 'size' => 128, 'key' => true, ), 
				'perms' => array ( 'type' => 'varchar', 'size' => 64, ), 
				'id' => array ( 'type' => 'varchar', 'size' => 32, ), 
			),
			'emailsignup'
		);
	}

}
