<?php
# automatically generated by makeclasses.php

class MailboxesEntity extends Entity {
	function __construct() {
		parent::__construct(
			LifelineDB::$db, 
			# $this->schema: for building forms among other things
			array ( 
				'transdate' => array ( 'type' => 'datetime', 'size' => 20, ), 
				'transaction' => array ( 'type' => 'double', ), 
				'vendor' => array ( 'type' => 'varchar', 'size' => 64, ), 
				'user' => array ( 'type' => 'varchar', 'size' => 32, ), 
				'amount' => array ( 'type' => 'float', ), 
				'notes' => array ( 'type' => 'varchar', 'size' => 255, ), 
				'name' => array ( 'type' => 'varchar', 'size' => 64, ), 
				'box' => array ( 'type' => 'int', 'size' => 11, ), 
			),
			'mailboxes'
		);
	}

}
