<?php
# automatically generated by makeclasses.php

class MessagesEntity extends Entity {
	function __construct() {
		parent::__construct(
			LifelineDB::$db, 
			# $this->schema: for building forms among other things
			array ( 
				'message' => array ( 'type' => 'varchar', 'size' => 255, 'key' => true, ), 
				'box' => array ( 'type' => 'varchar', 'size' => 32, ), 
				'callerid' => array ( 'type' => 'varchar', 'size' => 64, ), 
				'vid' => array ( 'type' => 'int', 'size' => 11, ), 
				'recorded' => array ( 'type' => 'datetime', ), 
			),
			'messages'
		);
	}

}
