<?php
# automatically generated by makeclasses.php

class MonthstransferEntity extends Entity {
	function __construct() {
		parent::__construct(
			LifelineDB::$db, 
			# $this->schema: for building forms among other things
			array ( 
				'transferred' => array ( 'type' => 'datetime', ), 
				'months' => array ( 'type' => 'int', 'size' => 11, ), 
				'fromvid' => array ( 'type' => 'int', 'size' => 11, ), 
				'tovid' => array ( 'type' => 'int', 'size' => 11, ), 
				'login' => array ( 'type' => 'varchar', 'size' => 64, ), 
			),
			'monthstransfer'
		);
	}

}
