<?php
# automatically generated by makeclasses.php

class NumrangeEntity extends Entity {
	function __construct() {
		parent::__construct(
			LifelineDB::$db, 
			# $this->schema: for building forms among other things
			array ( 
				'i' => array ( 'type' => 'int', 'size' => 11, ), 
			),
			'numrange'
		);
	}

}
