<?php
# automatically generated by makeclasses.php

class PaycodeEntity extends Entity {
	function __construct() {
		parent::__construct(
			LifelineDB::$db, 
			# $this->schema: for building forms among other things
			array ( 
				'code' => array ( 'type' => 'varchar', 'size' => 32, 'key' => true, ), 
				'months' => array ( 'type' => 'int', 'size' => 11, ), 
				'created' => array ( 'type' => 'datetime', ), 
				'used' => array ( 'type' => 'datetime', ), 
				'box' => array ( 'type' => 'varchar', 'size' => 16, ), 
			),
			'paycode'
		);
	}

}
