<?php
# automatically generated by makeclasses.php

class PaymentsRelation extends Relation {
	function __construct() {
		parent::__construct(
			LifelineDB::$db, 
			# $this->schema: for building forms among other things
			array ( 
				'PRIMARY KEY' => array ( 'box' => '', 'vid' => '', 'paidon' => '', 'login' => '', ), 
				'box' => array ( 'type' => 'varchar', 'size' => 32, ), 
				'vid' => array ( 'type' => 'int', 'size' => 11, ), 
				'paidon' => array ( 'type' => 'datetime', ), 
				'amount' => array ( 'type' => 'float', ), 
				'hst' => array ( 'type' => 'float', ), 
				'months' => array ( 'type' => 'int', 'size' => 11, ), 
				'login' => array ( 'type' => 'varchar', 'size' => 64, ), 
				'notes' => array ( 'type' => 'text', ), 
				'ip' => array ( 'type' => 'varchar', 'size' => 32, ), 
			),
			'payments'
		);
	}

}
