<?php
# automatically generated by makeclasses.php

class PayphonesEntity extends Entity {
	function __construct() {
		parent::__construct(
			LifelineDB::$db, 
			# $this->schema: for building forms among other things
			array ( 
				'number' => array ( 'type' => 'varchar', 'size' => 16, 'key' => true, ), 
				'wherefrom' => array ( 'type' => 'text', ), 
				'notes' => array ( 'type' => 'text', ), 
			),
			'payphones'
		);
	}

}
