<?php
# automatically generated by makeclasses.php

class Sync_callsEntity extends Entity {
	function __construct() {
		parent::__construct(
			LifelineDB::$db, 
			# $this->schema: for building forms among other things
			array ( 
				'synctime' => array ( 'type' => 'datetime', 'size' => 20, ), 
			),
			'sync_calls'
		);
	}

}
