<?php
# automatically generated by makeclasses.php

class TransactionsEntity extends Entity {
	function __construct() {
		parent::__construct(
			LifelineDB::$db, 
			# $this->schema: for building forms among other things
			array ( 
				'trans' => array ( 'type' => 'varchar', 'size' => 128, 'key' => true, ), 
				'time' => array ( 'type' => 'timestamp', 'size' => 20, ), 
				'vid' => array ( 'type' => 'int', 'size' => 11, ), 
				'table_name' => array ( 'type' => 'varchar', 'size' => 32, ), 
				'status' => array ( 'type' => 'varchar', 'size' => 32, ), 
				'box' => array ( 'type' => 'varchar', 'size' => 32, ), 
			),
			'transactions'
		);
	}

}
