<?php
# automatically generated by makeclasses.php

class UpdatesEntity extends Entity {
	function __construct() {
		parent::__construct(
			LifelineDB::$db, 
			# $this->schema: for building forms among other things
			array ( 
				'box' => array ( 'type' => 'varchar', 'size' => 32, ), 
				'months' => array ( 'type' => 'int', 'size' => 11, ), 
				'oldpaidto' => array ( 'type' => 'date', ), 
				'newpaidto' => array ( 'type' => 'date', ), 
				'paycode' => array ( 'type' => 'varchar', 'size' => 32, ), 
				'updated' => array ( 'type' => 'timestamp', 'size' => 20, ), 
				'login' => array ( 'type' => 'varchar', 'size' => 32, ), 
				'vid' => array ( 'type' => 'int', 'size' => 11, ), 
				'action' => array ( 'type' => 'varchar', 'size' => 128, ), 
				'app' => array ( 'type' => 'varchar', 'size' => 128, ), 
			),
			'updates'
		);
	}

}
