<?php
# automatically generated by makeclasses.php

class UsersEntity extends Entity {
	function __construct() {
		parent::__construct(
			LifelineDB::$db, 
			# $this->schema: for building forms among other things
			array ( 
				'login' => array ( 'type' => 'varchar', 'size' => 64, 'key' => true, ), 
				'password' => array ( 'type' => 'varchar', 'size' => 64, ), 
				'created' => array ( 'type' => 'timestamp', ), 
				'vid' => array ( 'type' => 'int', 'size' => 11, ), 
				'perms' => array ( 'type' => 'varchar', 'size' => 128, ), 
				'notes' => array ( 'type' => 'varchar', 'size' => 255, ), 
			),
			'users'
		);
	}

}
