<?php
# automatically generated by makeclasses.php

class Vendors_20100615Entity extends Entity {
	function __construct() {
		parent::__construct(
			LifelineDB::$db, 
			# $this->schema: for building forms among other things
			array ( 
				'vid' => array ( 'type' => 'int', 'size' => 11, ), 
				'vendor' => array ( 'type' => 'varchar', 'size' => 128, ), 
				'created' => array ( 'type' => 'timestamp', ), 
				'parent' => array ( 'type' => 'int', 'size' => 11, ), 
				'address' => array ( 'type' => 'varchar', 'size' => 128, ), 
				'phone' => array ( 'type' => 'varchar', 'size' => 128, ), 
				'contact' => array ( 'type' => 'varchar', 'size' => 128, ), 
				'email' => array ( 'type' => 'varchar', 'size' => 128, ), 
				'fax' => array ( 'type' => 'varchar', 'size' => 128, ), 
				'gstexempt' => array ( 'type' => 'int', 'size' => 11, ), 
				'rate' => array ( 'type' => 'float', ), 
				'months' => array ( 'type' => 'int', 'size' => 11, ), 
				'all_months' => array ( 'type' => 'int', 'size' => 11, ), 
				'pst_number' => array ( 'type' => 'varchar', 'size' => 128, ), 
				'gst_number' => array ( 'type' => 'varchar', 'size' => 128, ), 
				'credit_limit' => array ( 'type' => 'float', ), 
				'status' => array ( 'type' => 'varchar', 'size' => 32, ), 
				'notes' => array ( 'type' => 'text', ), 
			),
			'vendors_20100615'
		);
	}

}
